services:
    - type: web
      name: words-backend
      env: python
      plan: free
      buildCommand: pip install -r requirements.txt
      startCommand: python app.py
      envVars:
          - key: ENV
            value: production
          - key: PYTHON_VERSION
            value: 3.8.10
